// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByEnviX-FDw6MAqAt3DdFm5GTvXuKiwKE',
    appId: '1:894615157997:web:9e5b2fc5d3f0c7ceb5a0e4',
    messagingSenderId: '894615157997',
    projectId: 'kafiil-12b6c',
    authDomain: 'kafiil-12b6c.firebaseapp.com',
    databaseURL: 'https://kafiil-12b6c-default-rtdb.firebaseio.com',
    storageBucket: 'kafiil-12b6c.appspot.com',
    measurementId: 'G-TXXLDM8EZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaeOWlWf2tzbckvmdG7YjW2P7GA5DEbKA',
    appId: '1:894615157997:android:8ceb810270fa76ffb5a0e4',
    messagingSenderId: '894615157997',
    projectId: 'kafiil-12b6c',
    databaseURL: 'https://kafiil-12b6c-default-rtdb.firebaseio.com',
    storageBucket: 'kafiil-12b6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_qQCIi2C_OSCQRT0aJNhtdnYLOuInGn0',
    appId: '1:894615157997:ios:666f9761acc88e09b5a0e4',
    messagingSenderId: '894615157997',
    projectId: 'kafiil-12b6c',
    databaseURL: 'https://kafiil-12b6c-default-rtdb.firebaseio.com',
    storageBucket: 'kafiil-12b6c.appspot.com',
    iosClientId: '894615157997-0asg07thse2s7vpb6b2vii600pg71aeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.kafilmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_qQCIi2C_OSCQRT0aJNhtdnYLOuInGn0',
    appId: '1:894615157997:ios:666f9761acc88e09b5a0e4',
    messagingSenderId: '894615157997',
    projectId: 'kafiil-12b6c',
    databaseURL: 'https://kafiil-12b6c-default-rtdb.firebaseio.com',
    storageBucket: 'kafiil-12b6c.appspot.com',
    iosClientId: '894615157997-0asg07thse2s7vpb6b2vii600pg71aeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.kafilmobile',
  );
}
